# golangci-lint config
linters:
  disable-all: true
  enable:
    - bodyclose
    - bidichk
    - decorder
    - containedctx
    - contextcheck
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errchkjson
    - errname
    - execinquery
    - errorlint
    - exportloopref
    - exhaustive
    - goconst
    - godot
    - gocritic
    - gofmt
    - goimports
#    - gomnd
    - gocyclo
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - tenv
    - typecheck
    - unconvert
    - usestdlibvars
    - unparam
    - unused
    - whitespace
    - lll

linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  goimports:
    # ensure placement of imports with this prefix after all other imports
    # corresponds to `goimports -local`
    local-prefixes: github.com/ayoisaiah/f2
#  gomnd:
#    settings:
#      mnd:
#        # don't include the "operation" and "assign" checks
#        checks: argument,case,condition,return
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
  nestif:
    min-complexity: 15
  nolintlint:
    require-explanation: true
    require-specific: true
  lll:
    maxlength: 120

issues:
  fix: true
  exclude-rules:
    - path: _test\.go # disable some linters for test files
      linters:
        - gocyclo
        - gosec
        - dupl
    - linters:
        - gosec
      text: 'weak cryptographic primitive'
    - linters:
        - stylecheck
      text: 'error strings should not be capitalized'

  max-issues-per-linter: 0
  max-same-issues: 0

run:
  allow-parallel-runners: false
  issues-exit-code: 1
  timeout: 5m