version: build-{build}.{branch}

build: off

clone_folder: /usr/go/src/github.com/lifezq/goutils
shallow_clone: true

environment:
  GOPATH: /usr/go/

platform:
  - x64

install:
  - go version
  - go env
  
before_test:
  - go vet ./...

test_script:
  - go test ./...
  
deploy: off
